name: Lint & Test

on:
  push:
    branches:
      - "**"  # Runs on any push
  pull_request:
    branches:
      - "**"  # Runs on any PR

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Lint Image
        run: docker build --target=lint -t fastapi-lint .

      - name: Run Linter with Mounted .git Directory
        run: docker run --rm -v $(pwd)/.git:/code/.git fastapi-lint

  unit-tests:
    runs-on: ubuntu-latest
    needs: lint  # Only run if linting passes
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Test Image
        run: docker build --target=test -t fastapi-unit-test .

      - name: Run Unit Tests
        run: docker run --rm fastapi-unit-test
