name: Lint & Test

on:
  push:
    branches:
      - "**"  # Runs on any push
  pull_request:
    branches:
      - "**"  # Runs on any PR

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Pre-commit
        run: |
          python -m pip install --no-cache-dir --upgrade pre-commit
          pre-commit install

      - name: Run Pre-commit Hooks
        run: pre-commit run --all-files

  unit-tests:
    runs-on: ubuntu-latest
    needs: lint  # Only run if linting passes
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Test Image
        run: docker build --target=test -t fastapi-unit-test .

      - name: Run Unit Tests
        run: docker run --rm fastapi-unit-test
